name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create artifact
        run: |
          zip -r build.zip build/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.zip

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: <alienenergy>
          publish-profile: ${{ secrets.AZURE_HSS }}
          package: ${{ github.workspace }}/build.zip
